# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: legacy_aliases.yml }
parameters:
#    parameter_name: value

services:

    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Service\MarkdownTransformer:
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']


    AppBundle\Twig\MarkdownExtension:
        #arguments: ['@app.markdown_transformer']


    AppBundle\Security\LoginFormAuthenticator:

    AppBundle\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\Form\TypeExtension\HelpFormExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    app.encouraging_message_generator:
        class: AppBundle\Service\MessageGenerator
        arguments:
            - ['You can do it!', 'Dude, sweet!', 'Woot!']

    app.discouraging_message_generator:
        class: AppBundle\Service\MessageGenerator
        arguments:
            - ['We are *never* going to figure this out', 'Why even try again?', 'Facepalm']
